# Generated by Django 2.1.2 on 2019-02-22 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xixi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xxtable',
            name='single_or_double',
            field=models.CharField(choices=[('双周', '双周'), ('单周', '单周'), ('单双周', '单双周')], default='s', max_length=3, verbose_name='单双周'),
        ),
        migrations.AlterModelTable(
            name='xxtable',
            table='xxtimetable',
        ),
    ]
